### ISSUE TITLE
Client example not working: could not find `client` in `hyper_util

### ISSUE THREAD

**Issue by locnnil** [softprops/hyperlocal#74]
Client example isn't working: 

```bash
error[E0433]: failed to resolve: could not find `client` in `hyper_util`
   --> src/main.rs:148:17
    |
148 | use hyper_util::client::legacy::Client;
    |                 ^^^^^^ could not find `client` in `hyper_util`
```

Cargo.toml file:

```toml
[package]
name = "env-exporter"
version = "0.1.0"
edition = "2021"

[dependencies]
http-body-util = "0.1.2"
hyper = { version = "1.3", features = ["client"] }
hyper-util = "0.1.6"
hyperlocal = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.35", features = ["full"] }


[profile.release]
panic = "abort"
strip = true
opt-level = "z"
lto = true
codegen-units = 1

```

rustup toolchain: `x86_64-unknown-linux-musl`

**Comment by iamjpotts** [comment]
What version of `hyperlocal` are you trying to build with - current `main`?

Can you add some more context for reproducing this?

**Comment by locnnil** [comment]
@iamjpotts Sure, added in the description.

**Comment by iamjpotts** [comment]
Version `0.7` of `hyperlocal` should be considered unsupported at this point. Version `0.8` - which is still using 0.14 versions of `hyper` - is the latest published version.

If you want to use it with `hyper 1.x` (e.g. `hyper 1.3`), you'll need to setup your `Cargo.toml` to point at this repository for its `hyperlocal` dependency instead of using a version which would only be able to use versions published to crates.io.

**Comment by locnnil** [comment]
@iamjpotts thanks for letting me know! 

Now with the dependency on `Cargo.toml` like this:

```toml
[dependencies]
http-body-util = "0.1.2"
hyper = { version = "1.3", features = ["client"] }
hyper-util = "0.1.6"
hyperlocal = {git = "https://github.com/softprops/hyperlocal", branch = "main"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.35", features = ["full"] }

```

I'm having this error:

```bash
error[E0599]: no function or associated item named `unix` found for struct `Client` in the current scope
   --> src/main.rs:157:62
    |
157 |     let client: Client<UnixConnector, Full<Bytes>> = Client::unix();
    |                                                              ^^^^ function or associated item not found in `Client<_, _>`

```

Any ideia?

**Comment by iamjpotts** [comment]
I cannot reproduce your error.

I:

1. Ran `cargo new foo` to create a new application crate
2. Replaced the generated `Cargo.toml` witih the below snippet
3. Replaced the generated `src/main.rs` with the contents of [examples/client.rs](https://github.com/softprops/hyperlocal/blob/703fd917da67ddf1fd65c0a94e1ed1bd422bf1f6/examples/client.rs)
4. From inside `foo/` ran both `cargo b` and `cargo b --release`

`Cargo.toml`:

```toml
[package]
name = "foo"
version = "0.1.0"
edition = "2021"

[dependencies]
http-body-util = "0.1.2"
hyper = { version = "1.3", features = ["client"] }
hyper-util = "0.1.6"
hyperlocal = {git = "https://github.com/softprops/hyperlocal", branch = "main"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.35", features = ["full"] }

[profile.release]
panic = "abort"
strip = true
opt-level = "z"
lto = true
codegen-units = 1
```

```
$ rustc --version
rustc 1.78.0 (9b00956e5 2024-04-29)
```

Perhaps you could post a `gist` or a new public repo that reproduces this failure?
